refactor: prettier format
sergiofv/call-to-action-vi pull request #73
Opened 2022-01-20 15:33 UTC by sergiofv

2022-01-20 15:36 UTC, koepferd approved these changes

2022-02-28 12:55 UTC, koepferd requested changes

2022-02-28 12:55 UTC, koepferd commented on src/components/call-to-action/call-to-action.scss
> +.btn.dark {
please also use bem -> .btn-dark

also for --mid & --light

2022-02-28 12:55 UTC, koepferd commented on src/components/accordion-tab/accordion-tab.tsx
> +  @Prop() tabTitle: string;
I would not change this prop name.
In the scope the accordion tab it is still the title.

2022-02-28 12:55 UTC, koepferd commented on src/components/accordion-tab/accordion-tab.scss
> +details > summary {
As discussed: wrong selector here. Please use the add the summary & p styling directly in the details.

2022-02-28 12:55 UTC, koepferd commented on src/components/call-to-action/call-to-action.tsx
> +      buttonClassname: 'btn dark',
you can go with buttonClass & class as per convention.

2022-02-28 12:55 UTC, koepferd commented on src/components/call-to-action/call-to-action.tsx
> +            : renderFooter(null)}
*we've talked about this already ;-)

2022-03-14 10:17 UTC, sergiofv commented
New repo with all the changes specified and API fetch feature now available [here](https://github.com/sergiofv/homepage-call-to-action).

2022-03-15 13:09 UTC, closed without merging